apiVersion: v1
kind: ConfigMap
metadata:
  name: generic-config
data:
  dataStorage: /data
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: metrix
  name: metrix
spec:
  replicas: 2
  selector:
    matchLabels:
      run: metrix
  template:
    metadata:
      labels:
        run: metrix
    spec:
      containers:
      - image: metrix-image:v1
        name: metrix
        ports:
        - containerPort: 8080
        env:
          - name: METRIX_DATA_STORAGE
            valueFrom:
              configMapKeyRef:
                name: generic-config
                key: dataStorage
        volumeMounts:
        - mountPath: /data
          name: data-volume
      volumes:
      - name: data-volume
        hostPath:
          path: /data
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: metrix
  name: metrix
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: metrix
  type: NodePort

