apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: metrix
  name: metrix
spec:
  replicas: 1
  selector:
    matchLabels:
      run: metrix
  template:
    metadata:
      labels:
        run: metrix
    spec:
      containers:
      - image: metrix-image:v1
        name: metrix
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: metrix
  name: metrix
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: metrix
  type: NodePort

